"""
Task 15: Fine-tuning GPT-2 for Finance

Fine-tunes GPT-2 (124M params) on Indian financial text to generate
finance-domain responses. Uses HuggingFace Transformers + custom
financial dataset.

Install:
    pip install transformers datasets accelerate torch

Run:
    python finetune_gpt2_finance.py

Output: Saved model at ./gpt2-finance/
"""

import torch
from torch.utils.data import Dataset
import logging
import os

logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(message)s")
logger = logging.getLogger(__name__)


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# FINANCIAL TRAINING DATA
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

FINANCIAL_TEXTS = [
    # GST Knowledge
    "GSTIN is a 15-digit unique identification number assigned to every taxpayer registered under GST in India. The format is: 2 digits state code + 10 digits PAN + 1 entity code + 1 'Z' + 1 check digit. For example, 36AAJCC9783E1Z8 belongs to a business in Telangana (state code 36).",

    "Under GST, there are three types of taxes: CGST (Central GST) collected by the central government, SGST (State GST) collected by the state government for intra-state transactions, and IGST (Integrated GST) for inter-state transactions. For intra-state supply, CGST rate equals SGST rate, and their sum equals the total GST rate.",

    "A Tax Invoice must contain: supplier name and GSTIN, invoice number and date, recipient details, HSN/SAC code, description and quantity of goods, taxable value, tax rate and amount (CGST/SGST or IGST), total invoice value, place of supply, and whether reverse charge applies.",

    "Place of Supply determines whether a transaction is intra-state or inter-state. For goods, it is generally the location where delivery terminates. For services, it is usually the location of the recipient. If place of supply is in the same state as the supplier, CGST+SGST apply. If different state, IGST applies.",

    "Reverse charge mechanism means the recipient pays GST instead of the supplier. This applies to specified goods and services, import of services, and supplies from unregistered dealers exceeding the threshold. The recipient must self-assess the tax and pay it directly to the government.",

    # Indian Invoice Knowledge
    "Amazon India invoices contain: Tax Invoice/Bill of Supply header, Order Number (format: XXX-XXXXXXX-XXXXXXX), Invoice Number, Order Date, Invoice Date, Sold By details with GSTIN and PAN, Billing and Shipping addresses with state codes, HSN codes for each product, CGST/SGST or IGST breakdown, and total amount with Amount in Words.",

    "Flipkart invoices are generated by the seller, not Flipkart. They contain: Tax Invoice header, GSTIN of the seller, Order ID (format: ODXXXXXXXXXX), Invoice Number, PAN and CIN of the selling entity, product HSN/SAC codes, IGST for inter-state or CGST+SGST for intra-state transactions, and Grand Total.",

    "Swiggy generates two invoices per order: one from the restaurant (for food items with 5% GST) and one from Swiggy itself (for delivery and handling fees with 18% GST). The restaurant invoice contains FSSAI license number. Both invoices have the same Order ID for cross-reference.",

    "Zomato invoices follow the same pattern as Swiggy: restaurant invoice + platform fee invoice. Since Zomato rebranded to Eternal Limited, invoices show 'Eternal Limited (formerly known as Zomato Limited)'. Restaurant GSTIN and FSSAI are on the restaurant invoice, while Eternal's GSTIN is on the platform fee invoice.",

    # Banking Knowledge
    "Bank statements in India contain: Account holder name, Account number, IFSC code (4 letters + 0 + 6 alphanumeric), Branch name, Statement period, Opening and Closing balance, and transaction details with Date, Description, Debit/Credit amount, and Running balance.",

    "IFSC (Indian Financial System Code) is an 11-character alphanumeric code that uniquely identifies a bank branch. The first 4 characters represent the bank, the 5th character is always 0, and the last 6 characters identify the branch. For example, SBIN0001234 is State Bank of India.",

    # Accounting Basics
    "The fundamental accounting equation is: Assets = Liabilities + Equity. Every financial transaction affects at least two accounts (double-entry bookkeeping). Debits increase assets and expenses, while credits increase liabilities, equity, and revenue.",

    "Invoice processing in accounts payable involves: receiving the invoice, three-way matching (invoice vs purchase order vs goods receipt), coding to the correct GL account, approval workflow, and payment processing. Automation using OCR and AI reduces manual data entry errors and processing time.",

    "HSN (Harmonized System of Nomenclature) codes classify goods for GST purposes. They are 4, 6, or 8 digits. SAC (Services Accounting Code) classifies services. For example, HSN 85183011 is for wireless earphones, and SAC 996331 is for restaurant services.",

    "E-invoicing in India requires businesses with turnover above Rs 5 crore to generate invoices through the Invoice Registration Portal (IRP). Each e-invoice gets a unique IRN (Invoice Reference Number) and QR code. The IRN is a 64-character hash that ensures invoice authenticity.",

    # Financial Analysis
    "Key financial ratios: Current Ratio = Current Assets / Current Liabilities (ideal > 2), Debt-to-Equity = Total Debt / Shareholder Equity (lower is better), Gross Margin = (Revenue - COGS) / Revenue, Net Profit Margin = Net Income / Revenue, ROE = Net Income / Shareholder Equity.",

    "Working capital management involves optimizing the cash conversion cycle: Days Inventory Outstanding + Days Sales Outstanding - Days Payable Outstanding. Efficient invoice processing reduces DSO by ensuring timely billing and collection.",

    "TDS (Tax Deducted at Source) is deducted when making certain payments: salary (Section 192), interest (Section 194A), professional fees (Section 194J), rent (Section 194I), contract payments (Section 194C). The deductor must file TDS returns quarterly.",

    "Under Section 44AD of the Income Tax Act, businesses with turnover up to Rs 2 crore can opt for presumptive taxation, declaring 8% of gross receipts as taxable income (6% for digital transactions). This simplifies compliance for small businesses.",

    "PAN (Permanent Account Number) is a 10-character alphanumeric identifier issued by the Income Tax Department. Format: AAAAA9999A. The 4th character indicates the entity type: P for Individual, C for Company, F for Firm, H for HUF, T for Trust.",
]


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# DATASET
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

class FinanceDataset(Dataset):
    """Custom dataset for financial text fine-tuning."""

    def __init__(self, texts, tokenizer, max_length=512):
        self.encodings = []
        for text in texts:
            enc = tokenizer(
                text,
                truncation=True,
                max_length=max_length,
                padding="max_length",
                return_tensors="pt",
            )
            self.encodings.append({
                "input_ids": enc["input_ids"].squeeze(),
                "attention_mask": enc["attention_mask"].squeeze(),
                "labels": enc["input_ids"].squeeze(),
            })

    def __len__(self):
        return len(self.encodings)

    def __getitem__(self, idx):
        return self.encodings[idx]


# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# TRAINING
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

def train():
    from transformers import GPT2LMHeadModel, GPT2Tokenizer, TrainingArguments, Trainer

    output_dir = "./gpt2-finance"

    logger.info("Loading GPT-2 model and tokenizer...")
    tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
    model = GPT2LMHeadModel.from_pretrained("gpt2")

    # GPT-2 doesn't have a pad token — use EOS
    tokenizer.pad_token = tokenizer.eos_token
    model.config.pad_token_id = tokenizer.eos_token_id

    logger.info(f"GPT-2 loaded: {sum(p.numel() for p in model.parameters()):,} parameters")

    # Create dataset
    dataset = FinanceDataset(FINANCIAL_TEXTS, tokenizer)
    logger.info(f"Training on {len(dataset)} financial text samples")

    # Training config
    training_args = TrainingArguments(
        output_dir=output_dir,
        num_train_epochs=5,
        per_device_train_batch_size=2,
        gradient_accumulation_steps=4,
        learning_rate=5e-5,
        warmup_steps=10,
        logging_steps=5,
        save_steps=50,
        save_total_limit=2,
        fp16=torch.cuda.is_available(),
        report_to="none",
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=dataset,
    )

    logger.info("Starting fine-tuning...")
    trainer.train()

    # Save
    model.save_pretrained(output_dir)
    tokenizer.save_pretrained(output_dir)
    logger.info(f"Model saved to {output_dir}")

    # Test generation
    logger.info("\n=== Testing generation ===")
    prompts = [
        "GSTIN is a",
        "Under GST in India,",
        "The key financial ratios are",
        "An Amazon India invoice contains",
    ]

    model.eval()
    for prompt in prompts:
        inputs = tokenizer(prompt, return_tensors="pt")
        with torch.no_grad():
            outputs = model.generate(
                **inputs,
                max_new_tokens=100,
                temperature=0.7,
                do_sample=True,
                top_p=0.9,
                pad_token_id=tokenizer.eos_token_id,
            )
        generated = tokenizer.decode(outputs[0], skip_special_tokens=True)
        print(f"\nPrompt: {prompt}")
        print(f"Generated: {generated[:200]}...")


if __name__ == "__main__":
    train()
